schema = 3

[mod]
  [mod."github.com/antonmedv/expr"]
    version = "v1.9.0"
    hash = "sha256-YEOreSbIXxyDwE2LqjAABxfdeh1eudCcpqh2l/Lpsq4="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.1.2"
    hash = "sha256-YV9SmXDtmmgQylQUfrUgQLAPfqYexcHxegMBT+IX9qM="
  [mod."github.com/choria-io/fisk"]
    version = "v0.3.0"
    hash = "sha256-H8ZmOdyKW+KvvMH+qLB2+uBY1dy06WnpHvrmcjkHKwA="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.2"
    hash = "sha256-IVwooaIo46iq7euSSVWTBAdKd+2DUaJ67MtBao1DpBI="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.1"
    hash = "sha256-ystDNStxR90j4CK+AMcEQ5oyYFRgWoGdvWlS0XQMDLQ="
  [mod."github.com/nats-io/jsm.go"]
    version = "v0.0.35"
    hash = "sha256-g1ImrL82JwdRf9Ym3QOm46M+OLDNHo3jPZB5Fh/uymg="
  [mod."github.com/nats-io/nats.go"]
    version = "v1.22.2-0.20230113145119-dfc537e51917"
    hash = "sha256-EKYkawkqlT+KhjyvFwv1JDQcL2wul6wYEwCd5lOWYCs="
  [mod."github.com/nats-io/nkeys"]
    version = "v0.3.0"
    hash = "sha256-63yGhXiKvDhJDnTbFQJXyl2yvmvZ2OXedizLzsaqixs="
  [mod."github.com/nats-io/nuid"]
    version = "v1.0.1"
    hash = "sha256-7wddxVz3hnFg/Pf+61+MtQJJL/l8EaC8brHoNsmD64c="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.14.0"
    hash = "sha256-dpgGV8C30ZCn7b9mQ+Ye2AfPXTIuHLQbl2olMKzJKxA="
  [mod."github.com/prometheus/client_model"]
    version = "v0.3.0"
    hash = "sha256-vP+miJfsoK5UG9eug8z/bhAMj3bwg66T2vIh8WHoOKU="
  [mod."github.com/prometheus/common"]
    version = "v0.37.0"
    hash = "sha256-B2v0WsP8uKWYBpZcrog/sQXStIXwWZcVLmfPgnh1ZZA="
  [mod."github.com/prometheus/procfs"]
    version = "v0.8.0"
    hash = "sha256-hgrilokQsXCOCCvwgOSfuErxoFAQpXM/+zNJKcMVHyM="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."golang.org/x/crypto"]
    version = "v0.5.0"
    hash = "sha256-5L4rCFZ0IMT9aQIeMbfOFbhwi03nXE/EeWuXup+Aeoc="
  [mod."golang.org/x/sys"]
    version = "v0.4.0"
    hash = "sha256-jchMzHCH5dg+IL/F+LqaX/fyAcB/nvHQpfBjqwaRJH0="
  [mod."google.golang.org/protobuf"]
    version = "v1.28.1"
    hash = "sha256-sTJYgvlv5is7vHNxcuigF2lNASp0QonhUgnrguhfHSU="
